import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Read API key from .env
function getApiKey() {
  const envPath = path.join(__dirname, '..', '.env');
  const envContent = fs.readFileSync(envPath, 'utf-8');
  const match = envContent.match(/VITE_PEXELS_API_KEY=(.+)/);
  return match ? match[1].trim() : null;
}

const API_KEY = getApiKey();
if (!API_KEY) {
  console.error('Error: VITE_PEXELS_API_KEY not found in .env');
  process.exit(1);
}

// All states with their landmark search keywords
const states = [
  { name: 'Jammu and Kashmir', query: 'Dal Lake Kashmir' },
  { name: 'Himachal Pradesh', query: 'Shimla mountains' },
  { name: 'Punjab', query: 'Golden Temple Amritsar' },
  { name: 'Chandigarh', query: 'Rock Garden Chandigarh' },
  { name: 'Uttarakhand', query: 'Kedarnath temple' },
  { name: 'Haryana', query: 'Kurukshetra temple' },
  { name: 'Delhi', query: 'Red Fort Delhi' },
  { name: 'Rajasthan', query: 'Hawa Mahal Jaipur' },
  { name: 'Uttar Pradesh', query: 'Taj Mahal Agra' },
  { name: 'Bihar', query: 'Bodh Gaya temple' },
  { name: 'Sikkim', query: 'Rumtek monastery Sikkim' },
  { name: 'Arunachal Pradesh', query: 'Tawang monastery' },
  { name: 'Nagaland', query: 'Hornbill festival Nagaland' },
  { name: 'Manipur', query: 'Loktak Lake Manipur' },
  { name: 'Mizoram', query: 'Aizawl Mizoram' },
  { name: 'Tripura', query: 'Ujjayanta Palace Tripura' },
  { name: 'Meghalaya', query: 'Living root bridge Meghalaya' },
  { name: 'Assam', query: 'Kamakhya temple Assam' },
  { name: 'West Bengal', query: 'Victoria Memorial Kolkata' },
  { name: 'Jharkhand', query: 'Hundru Falls Jharkhand' },
  { name: 'Odisha', query: 'Konark Sun Temple' },
  { name: 'Chhattisgarh', query: 'Chitrakote waterfall Chhattisgarh' },
  { name: 'Madhya Pradesh', query: 'Khajuraho temple' },
  { name: 'Gujarat', query: 'Rann of Kutch' },
  { name: 'Maharashtra', query: 'Gateway of India Mumbai' },
  { name: 'Andhra Pradesh', query: 'Tirupati temple' },
  { name: 'Telangana', query: 'Charminar Hyderabad' },
  { name: 'Karnataka', query: 'Mysore Palace' },
  { name: 'Goa', query: 'Goa beach church' },
  { name: 'Kerala', query: 'Backwaters Kerala' },
  { name: 'Tamil Nadu', query: 'Meenakshi temple Madurai' },
  { name: 'Andaman and Nicobar Islands', query: 'Andaman beach coral' },
  { name: 'Lakshadweep', query: 'Lakshadweep island beach' },
  { name: 'Puducherry', query: 'Puducherry beach temple' },
  { name: 'Dadra and Nagar Haveli', query: 'Dadra Nagar Haveli' },
  { name: 'Daman and Diu', query: 'Daman beach fort' },
];

const FALLBACK_IMAGE = 'https://source.unsplash.com/800x600/?India,heritage';
const PEXELS_API = 'https://api.pexels.com/v1/search';

async function fetchImageForState(state) {
  try {
    const response = await fetch(
      `${PEXELS_API}?query=${encodeURIComponent(state.query)}&per_page=1`,
      {
        headers: { Authorization: API_KEY },
      }
    );

    if (!response.ok) {
      console.warn(`⚠️  Pexels API error for ${state.name}: ${response.status}`);
      return { ...state, image: FALLBACK_IMAGE, source: 'fallback' };
    }

    const data = await response.json();
    if (data.photos && data.photos.length > 0) {
      const imageUrl = data.photos[0].src.large;
      console.log(`✓ ${state.name}: ${imageUrl}`);
      return { ...state, image: imageUrl, source: 'pexels' };
    } else {
      console.warn(`⚠️  No images found for ${state.name}, using fallback`);
      return { ...state, image: FALLBACK_IMAGE, source: 'fallback' };
    }
  } catch (error) {
    console.error(`✗ Error fetching for ${state.name}:`, error.message);
    return { ...state, image: FALLBACK_IMAGE, source: 'fallback' };
  }
}

async function main() {
  console.log(`🔄 Fetching images for ${states.length} states/UTs...`);
  console.log('━'.repeat(60));

  const results = await Promise.all(states.map(fetchImageForState));

  // Build the mapImages object
  const mapImages = {};
  results.forEach(({ name, image }) => {
    mapImages[name] = image;
  });

  // Write to file
  const outputPath = path.join(__dirname, '..', 'src', 'data', 'mapImages.js');
  const fileContent = `// Auto-generated by scripts/fetchMapImages.js
// Do not edit manually
export const mapImages = ${JSON.stringify(mapImages, null, 2)};
`;

  fs.writeFileSync(outputPath, fileContent);

  console.log('━'.repeat(60));
  console.log(`✅ Done! Saved ${results.length} images to src/data/mapImages.js`);

  // Summary
  const pexelsCount = results.filter((r) => r.source === 'pexels').length;
  const fallbackCount = results.filter((r) => r.source === 'fallback').length;
  console.log(`   Pexels: ${pexelsCount}, Fallback: ${fallbackCount}`);
}

main().catch(console.error);
